export const divGallery = document.querySelector('.gallery')
export const sectionCategories = document.querySelector('.categories')
export const buttonAll = document.getElementById('all')
export const aLogin = document.getElementById('aLogin')
export const banner = document.querySelector('.banner')
export const header = document.querySelector('header')
export const editModal = document.getElementById('edit-modal')
// PAGE LOGIN
export const formLogin = document.querySelector("#form-login")
export const email = document.querySelector("#email")
export const password = document.querySelector("#password")
// MODAL
export const modal = document.getElementById('modal')
export const modalBtnClose = document.getElementById('modal-btn-close')
export const modalGallery = document.querySelector('#modal .gallery')
export const btnAddPicture = document.getElementById('btn-add-picture')
export const formAddPicture = document.getElementById('form-add-picture')
export const btnArrowBack = document.getElementById('modal-btn-back')