export const divGallery = document.querySelector('.gallery')
export const sectionCategories = document.querySelector('.categories')
export const buttonAll = document.getElementById('all')
export const aLogin = document.getElementById('aLogin')
export const banner = document.querySelector('.banner')
export const header = document.querySelector('header')
export const editModal = document.getElementById('edit-modal')
// PAGE LOGIN
export const formLogin = document.querySelector("#form-login")
export const email = document.querySelector("#email")
export const password = document.querySelector("#password")
